[PRM-1017]: added API1812 feature switch
hmrc/penalties pull request #100
Opened 2022-02-07 15:34 UTC by BackRowOla

2022-02-08 10:33 UTC, LewisMitchell requested changes
I've raised some points here, however some may be invalidated when its rebased 😄

2022-02-08 10:33 UTC, LewisMitchell commented on app/config/AppConfig.scala
> +    else etmpBase + "/penalties/details/"
The URL should be /penalty/details/VATC/VRN/<vrn>

2022-02-08 10:33 UTC, LewisMitchell commented on app/featureSwitches/FeatureSwitch.scala
> +  override val name: String = s"${FeatureSwitch.prefix}.call-api-1812-etmp"
An entry is needed in application.conf

2022-02-08 10:33 UTC, LewisMitchell commented on app/utils/RegimeHelper.scala
> +  def constructMTDVATCUrl(vrn: String): String = s"VATC/VRN/$vrn"
I'm not sure what we are doing with this?

2022-02-09 09:41 UTC, BackRowOla commented
QA and staging PR's
https://github.com/hmrc/app-config-qa/pull/14146/files
https://github.com/hmrc/app-config-staging/pull/9888

2022-02-09 10:29 UTC, LewisMitchell approved these changes

2022-02-09 10:30 UTC, merged