PRM-821 ETMP Payload with Array of PenaltyPeriod in LSP and LSPP
hmrc/penalties pull request #80
Opened 2021-11-12 07:56 UTC by ruthdas03

2021-11-15 09:57 UTC, LewisMitchell requested changes
Looks good, does this pass the AT's? If not, it will probably have to wait until the AT's have been updated

2021-11-15 09:57 UTC, LewisMitchell commented on app/services/ETMPService.scala
> +                period => penaltyPeriodHelper.sortedPenaltyPeriod(period).head.startDate.toLocalDate == penaltyPeriod._1 && penaltyPeriodHelper.sortedPenaltyPeriod(period).head.endDate.toLocalDate ==
Could we perhaps rename `period =>` to `periods =>`

2021-11-15 09:57 UTC, LewisMitchell commented on app/utils/PenaltyPeriodHelper.scala
> +class PenaltyPeriodHelper {
Rather than making this a class, could you make it an object? Then you don't need to inject it into the class parameters

2021-11-15 09:59 UTC, ruthdas03 commented
> Looks good, does this pass the AT's? If not, it will probably have to wait until the AT's have been updated

Sorry the AT isn't updated yet.

2021-11-15 10:03 UTC, LewisMitchell requested changes
Could you also have a test - probably an integration test to ensure we can parse a payload with multiple periods for a penalty?

2021-11-15 16:04 UTC, LewisMitchell requested changes

2021-11-15 16:04 UTC, LewisMitchell commented on it/controllers/AppealsControllerISpec.scala
> +    "call ETMP and compare the penalty ID provided and the penalty ID in the payload with multiple Penalty Period - return OK if there is a match" in {
I think this should be:
```suggestion
    "call ETMP and compare the penalty ID provided and the penalty ID in the payload - returning the oldest VAT period if there is multiple periods present" in {
```

2021-11-15 16:04 UTC, LewisMitchell commented on it/controllers/ETMPControllerISpec.scala
> +  val etmpPayloadWithMultipleLSP_InSameCalenderMonth: JsValue = Json.parse(
Could you rename this to:
```suggestion
  val etmpPayloadWithMultipleLSPInSameCalenderMonth: JsValue = Json.parse(
```

2021-11-15 16:04 UTC, LewisMitchell commented on it/controllers/ETMPControllerISpec.scala
> +  val etmpPayloadWithMultipleLSPP_InSameCalenderMonth: JsValue = Json.parse(
Could you rename this to:
```suggestion
  val etmpPayloadWithMultipleLSPPInSameCalenderMonth: JsValue = Json.parse(
```

2021-11-17 08:29 UTC, LewisMitchell approved these changes

2021-11-18 15:54 UTC, merged